# .github/workflows/ci.yml
name: React Native CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.9.0

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
