name: React Native CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.9.0

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

  # deploy-android:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 23.9.0

  #     - name: Install Dependencies
  #       run: npm install --legacy-peer-deps

  #     - name: Set up Java
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: "temurin"
  #         java-version: "17"

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: "3.1"

  #     - name: Install Fastlane dependencies
  #       run: cd android && bundle install

  #     - name: Decode Google Play JSON credentials
  #       run: |
  #         mkdir -p android/fastlane
  #         echo "${{ secrets.GOOGLE_PLAY_JSON }}" > android/fastlane/play-upload.json

  #     - name: Build and Deploy to Play Store
  #       working-directory: android
  #       run: bundle exec fastlane beta
  # deploy-ios:
  #   needs: build-and-test
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 23.9.0

  #     - name: Install Dependencies
  #       run: npm install --legacy-peer-deps

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.1

  #     - name: Install Fastlane dependencies
  #       run: cd ios && bundle install

  #     - name: Decode App Store Connect API Key
  #       run: |
  #         mkdir -p ios/fastlane
  #         echo "${{ secrets.APP_STORE_API_KEY_BASE64 }}" | base64 --decode > ios/fastlane/AuthKey.p8

  #     - name: Set Fastlane Environment Variables
  #       run: |
  #         echo "APP_STORE_KEY_ID=${{ secrets.APP_STORE_KEY_ID }}" >> $GITHUB_ENV
  #         echo "APP_STORE_ISSUER_ID=${{ secrets.APP_STORE_ISSUER_ID }}" >> $GITHUB_ENV
  #         echo "APP_STORE_API_KEY_PATH=ios/fastlane/AuthKey.p8" >> $GITHUB_ENV

  #     - name: Deploy to TestFlight
  #       working-directory: ios
  #       run: bundle exec fastlane beta
